# Project identification
sonar.projectKey=optmsg_app
sonar.projectName=OPTMSG
sonar.projectVersion=1.0
sonar.organization=optmsg
# SonarQube Server URL
sonar.host.url=https://sonarcloud.io

# Authentication (for SonarCloud or secured server)
sonar.login=9b9b5e56bea46d9fa35a17ff571b6f82cf78d3c3

# Source settings
sonar.sources=lib
sonar.tests=test
sonar.exclusions=build/**, android/**, ios/**

# Dart analyzer report (optional)
sonar.dart.analyzer.report=analyzer-report.json

# Test & coverage reports
sonar.junit.reportPaths=build/test-results/test
#sonar.coverageReportPaths=coverage/lcov.info
sonar.dart.coverage.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8