// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // W-7: The web config is ENV-aware so it always matches firebase-config.js
  // and the backend's Firebase Admin SDK.  The three must point to the same
  // project or FCM token delivery silently fails.
  //
  // Staging (default): optmsg-staging  → messagingSenderId 1004260439071
  // Production:        opt-msg-app     → messagingSenderId 403388879371
  //
  // Build flags:
  //   Staging:    flutter run/build ... --dart-define=ENV=stag   (or omit)
  //   Production: flutter run/build ... --dart-define=ENV=prod
  static FirebaseOptions get web {
    const env = String.fromEnvironment('ENV', defaultValue: 'stag');
    if (env == 'prod') {
      return const FirebaseOptions(
        apiKey: 'AIzaSyCP6iatDQx6MbFl8Vcs0MldsDcS-3MDnO0',
        appId: '1:403388879371:web:c990f10c6a37e5b315ad0e',
        messagingSenderId: '403388879371',
        projectId: 'opt-msg-app',
        authDomain: 'opt-msg-app.firebaseapp.com',
        storageBucket: 'opt-msg-app.firebasestorage.app',
        measurementId: 'G-VST4B7FVFE',
      );
    }
    // staging / dev (default)
    return const FirebaseOptions(
      apiKey: 'AIzaSyAOn7udVV71xCFutIQxmisE54ip27bjbf4',
      appId: '1:1004260439071:web:17ae34a9ca726eb91f112a',
      messagingSenderId: '1004260439071',
      projectId: 'optmsg-staging',
      authDomain: 'optmsg-staging.firebaseapp.com',
      storageBucket: 'optmsg-staging.firebasestorage.app',
    );
  }

  static FirebaseOptions get android {
    const env = String.fromEnvironment('ENV', defaultValue: 'stag');
    if (env == 'prod') {
      return const FirebaseOptions(
        apiKey: 'AIzaSyA6wu4t8R8z4NMtk5B1Aghp0oceHR5dIhE',
        appId: '1:403388879371:android:926ffda9fb4b034c15ad0e',
        messagingSenderId: '403388879371',
        projectId: 'opt-msg-app',
        storageBucket: 'opt-msg-app.firebasestorage.app',
      );
    }
    // staging / dev (default)
    return const FirebaseOptions(
      apiKey: 'AIzaSyAj-32Ny-I6L0xK7IYRJyqJJZ3VHm5uQ9s',
      appId: '1:1004260439071:android:b7b3d359c066a2051f112a',
      messagingSenderId: '1004260439071',
      projectId: 'optmsg-staging',
      storageBucket: 'optmsg-staging.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    const env = String.fromEnvironment('ENV', defaultValue: 'stag');
    if (env == 'prod') {
      return const FirebaseOptions(
        apiKey: 'AIzaSyBjR04j5UP2qzrzijfgrr4LwUqk5eLafwQ',
        appId: '1:403388879371:ios:da9c442bde51de8c15ad0e',
        messagingSenderId: '403388879371',
        projectId: 'opt-msg-app',
        storageBucket: 'opt-msg-app.firebasestorage.app',
        iosBundleId: 'com.optmsg.mail',
      );
    }
    // staging / dev (default)
    return const FirebaseOptions(
      apiKey: 'AIzaSyCa3UuV2BG4DevzetwWtB_It0kEte2u9gc',
      appId: '1:1004260439071:ios:8a1f4fc7fadc6b601f112a',
      messagingSenderId: '1004260439071',
      projectId: 'optmsg-staging',
      storageBucket: 'optmsg-staging.firebasestorage.app',
      iosBundleId: 'com.optmsg.stag',
    );
  }
}
